apiDir: "../aixtor-employee-headless-api/src/main/java"
apiPackagePath: "com.aixtor.training.liferay.employee.headless"
application:
    baseURI: "/aixtor-employee-headless"
    className: "AixtorEmployeeHeadlessApplication"
    name: "AixtorEmployeeHeadless"
author: "shani.patel"
# clientDir: "../aixtor-employee-headless-client/src/main/java"
# testDir: "../aixtor-employee-headless-test/src/testIntegration/java"